config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "/home/about" => "homes#about"
  
  resources :books
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller? 

  private

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/about.html.erb
<main>
    <p id="notice"></p>
    <div class='container'>
    <div class='row'>
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
    </div>
    </div>
</main>

app/views/homes/top.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
      <button type="button" class="btn btn-outline-primary w-100"><%= link_to "Log in", new_user_session_path %></button>
      </div>
        <div class="row">
      <button type="button" class="btn btn-outline-success w-100"><%= link_to "Sign Up", new_user_registration_path %></button>
      </div>
      </div>
    </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2525</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
  <% if flash[:notice] %>
    <div class="notification is-info">
      <p class="notice"><%= notice %></p>
    </div>
  <% end %>
  <% if flash[:alert] %>
    <div class="notification is-denger">
      <p class="alert"><%= alert %></p>
    </div>
  <% end %>

  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
  <% if user_signed_in? %>
      <li><a class="fas fa-home nav-link text-light" href="<%= user_path(current_user.id) %>"> home</a></li>
      <li><a class="fas fa-users nav-link text-light" href="/users"> Users</a></li>
      <li><a class="fas fa-book-open nav-link text-light" href="/books"> Books</a></li>
      
      <li><a class="fas fa-sign-out-alt nav-link text-light" rel="nofollow" data-method="delete" href="/users/sign_out"> logout</a></li>
  <% else %>
      <li><a class="fas fa-home nav-link text-light" href="/"> Home</a></li>
      <li><a class="fas fa-link nav-link text-light" href="/home/about"> About</a></li>
      <li><a class="fas fa-user-plus nav-link text-light" href="/users/sign_up"> sign up</a></li>
      <li><a class="fas fa-sign-in-alt nav-link text-light" href="/users/sign_in"> login</a></li>
  <% end %>
        </ul>
      </div>
    </div>
    </nav>
  </header>
  <%= yield %>
  <footer class="footer">
    <div class='container mt-5'>
      <div class='row'>
	      <div class='mx-auto'>
		      <p>CopyRight Infratop.inc</p>
	      </div>
      </div>
    </div>
  </footer>
</body>
</html>